api_platform:
  mapping:
    paths:
      - '%kernel.project_dir%/config/packages/api_platform'
  patch_formats:
    json:
      - 'application/merge-patch+json'
  formats:
    jsonld:
      mime_types:
        - 'application/ld+json'
    html:
      mime_types:
        - 'text/html'
    json:
      mime_types:
        - 'application/json'
  error_formats:
    jsonproblem:
      mime_types:
        - 'application/problem+json'
  swagger:
    versions: [ 3 ]
